# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Energy
                                 A QGIS plugin
 Energie 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-27
        copyright            : (C) 2022 by die STEG Stadtentwicklung GmbH
        email                : mohammad.hosseingholizadeh@steg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Energy class from file Energy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .energy import Energy
    return Energy(iface)
